package dev.electrolyte.expandedtic.config;

import dev.electrolyte.expandedtic.ExpandedTiC;
import dev.toma.configuration.config.Config;
import dev.toma.configuration.config.Configurable;
import dev.toma.configuration.config.UpdateRestrictions;

@Config(id = ExpandedTiC.MOD_ID)
public final class ETModConfig {

    @Configurable
    @Configurable.Comment({"Configuration related to GT material generation.", "The following configuration options ONLY affect GT materials generated by this mod, due to the way they are generated.", "Non-gt materials, HAVE NO EFFECT HERE."})
    @Configurable.Synchronized
    @Configurable.UpdateRestriction(UpdateRestrictions.MAIN_MENU)
    public GTMaterialGeneration gtMaterialGeneration = new GTMaterialGeneration();
    public static class GTMaterialGeneration {
        @Configurable
        @Configurable.Comment("Gregtech Materials to ignore generating tinker's material information for")
        public String[] ignoredGTMaterials = new String[] {
                "bronze", "cobalt", "copper", "diamond", "flint", "invar", "iron", "netherite", "polybenzimidazole", "polyethylene", "polytetrafluoroethylene", "rose_gold", "rubber", "steel", "silicone_rubber", "styrene_butadiene_rubber", "wood"
        };

        @Configurable
        @Configurable.Comment("Generate extruder recipes for material parts?")
        public boolean generateExtruderRecipes = true;

        @Configurable
        @Configurable.Comment("Generate fluid solidifier recipes for material parts?")
        public boolean generateFluidSolidificationRecipes = false;

        @Configurable
        @Configurable.Comment({"Disable default material definition for the following GT materials", "Useful if you want to change the default material definition for a specific material."})
        public String[] ignoredDefaultMatDefGen = new String[]{};

        @Configurable
        @Configurable.Comment({"Disable default material stats for the following GT materials", "Useful if you want to change the default material stats for a specific material."})
        public String[] ignoredDefaultMatStatsGen = new String[]{};

        @Configurable
        @Configurable.Comment({"Disable default material traits for the following GT materials", "Useful if you want to change the default material traits for a specific material."})
        public String[] ignoredDefaultMatTraitsGen = new String[]{};

        @Configurable
        @Configurable.Comment("Global Modifiers for head materials")
        public HeadModifiers headModifiers = new HeadModifiers();

        public static class HeadModifiers {
            @Configurable
            @Configurable.Comment("Head durability modifier")
            public float headDurabilityModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Head mining speed modifier")
            public float headMiningSpeedModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Head attack damage modifier")
            public float headAttackDamageModifier = 1.0f;
        }

        @Configurable
        @Configurable.Comment("Global Modifiers for limb materials")
        public LimbModifiers limbModifiers = new LimbModifiers();

        public static class LimbModifiers {
            @Configurable
            @Configurable.Comment("Limb durability modifier")
            public float limbDurabilityModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Limb draw speed modifier")
            public float limbDrawSpeedModifier = 0.5f;

            @Configurable
            @Configurable.Comment("Limb velocity modifier")
            public float limbVelocityModifier = 0.45f;

            @Configurable
            @Configurable.Comment("Limb accuracy modifier")
            public float limbAccuracyModifier = 0.6f;
        }

        @Configurable
        @Configurable.Comment("Global Modifiers for grip materials")
        public GripModifiers gripModifiers = new GripModifiers();

        public static class GripModifiers {
            @Configurable
            @Configurable.Comment("Grip durability modifier")
            public float gripDurabilityModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Grip accuracy modifier")
            public float gripAccuracyModifier = 0.6f;

            @Configurable
            @Configurable.Comment("Grip melee damage modifier")
            public float gripMeleeDamageModifier = 0.1f;
        }

        @Configurable
        @Configurable.Comment("Global Modifiers for handle materials")
        public HandleModifiers handleModifiers = new HandleModifiers();

        public static class HandleModifiers {
            @Configurable
            @Configurable.Comment("Handle durability modifier")
            @Configurable.DecimalRange(min = 0.1f)
            public float handleDurabilityModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Handle mining speed modifier")
            @Configurable.DecimalRange(min = 0.1f)
            public float handleMiningSpeedModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Handle attack damage modifier")
            @Configurable.DecimalRange(min = 0.1f)
            public float handleAttackDamageModifier = 1.0f;

            @Configurable
            @Configurable.Comment("Handle attack speed modifier")
            @Configurable.DecimalRange(min = 0.1f)
            public float handleAttackSpeedModifier = 1.0f;
        }
    }
}
